#
api_key='BHUzFj8DAKKjNUfA3e'
api_secret='L5ZvG0DDrSNooVRyjgPM1JckoXXQ1FJ9ICtK'


#testing
# api_key= 'SWHHBPWKWEKFNAGABH'
# api_secret= 'CBHLKKRBOZNFPKXCXZEVLQBYFOPIVPQRYYYP'

#api_secret= 'XZEBUCDMDBYRRHSHHIWLAZUWZWSHRRDCNOTH'